version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ExamBotv13"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-855935ly5yob"
s3_prefix = "ExamBotv13"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

